import { ChallengeTemplate } from '@/types/challenges';

export const CHALLENGE_TEMPLATES: ChallengeTemplate[] = [
    {
        id: 'subtle-tension',
        title: 'Subtle tension',
        prompt: 'Capture something in your day that carries subtle tension.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'gentle-chaos',
        title: 'Gentle chaos',
        prompt: 'Capture a moment of gentle chaos in your environment.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'nostalgic-warmth',
        title: 'Nostalgic warmth',
        prompt: 'Capture something that carries nostalgic warmth today.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'earned-rest',
        title: 'Earned rest',
        prompt: 'Capture a scene that feels like earned rest.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'early-momentum',
        title: 'Early momentum',
        prompt: 'Capture something that set the tone for your morning.',
        type: 'observational',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'quiet-courage',
        title: 'Quiet courage',
        prompt: 'Capture something small that took courage today.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'held-together',
        title: 'Held together',
        prompt: "Capture something that looks like it's being held together for now.",
        type: 'observational',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'soft-relief',
        title: 'Soft relief',
        prompt: 'Capture the first thing that gave you a bit of relief today.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'mental-noise',
        title: 'Mental noise',
        prompt: 'Capture something that matches the mental noise of today.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'small-beauty',
        title: 'Small beauty',
        prompt: 'Capture a tiny piece of beauty you might normally ignore.',
        type: 'environmental',
        isActive: true,
        cooldownDays: 5,
    },
    {
        id: 'almost-annoyed',
        title: 'Almost annoyed',
        prompt: 'Capture a moment that almost tipped you into annoyance.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'spark-of-curiosity',
        title: 'Spark of curiosity',
        prompt: 'Capture something that made you unexpectedly curious today.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'quiet-pride',
        title: 'Quiet pride',
        prompt: 'Capture something that makes you quietly proud.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'out-of-place',
        title: 'Out of place',
        prompt: 'Capture something that feels slightly out of place in your environment.',
        type: 'environmental',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'unfinished-business',
        title: 'Unfinished business',
        prompt: 'Capture something that represents unfinished business from today.',
        type: 'observational',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'anchor-spot',
        title: 'Anchor spot',
        prompt: 'Capture the spot that grounded you the most today.',
        type: 'environmental',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'hidden-mess',
        title: 'Hidden mess',
        prompt: "Capture a hidden mess that most people wouldn't notice.",
        type: 'observational',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'on-standby',
        title: 'On standby',
        prompt: "Capture something that feels like it's waiting for its moment.",
        type: 'observational',
        isActive: true,
        cooldownDays: 7,
    },
    {
        id: 'soft-connection',
        title: 'Soft connection',
        prompt: 'Capture something that made you feel a bit less alone today.',
        type: 'emotional',
        isActive: true,
        cooldownDays: 10,
    },
    {
        id: 'end-of-day-trace',
        title: 'End-of-day trace',
        prompt: 'Capture a trace of your day that will be gone by tomorrow.',
        type: 'observational',
        isActive: true,
        cooldownDays: 10,
    },
];
