/**
 * Shared types for the Unpack feature — a Plus-only guided reflection flow that
 * turns a quick thought / photo / voice note / shared link into a polished,
 * journal-style entry after 3 clarifying questions.
 *
 * These types are used by the transient flow store (`lib/unpackStore.ts`), the
 * flow screens (`app/unpack/*`), the client service (`services/unpackClient.ts`),
 * and the saved-entry payload persisted on `entries.unpack_payload`.
 */

/** The original entry type the Unpack flow was launched from. */
export type UnpackEntryType = 'text' | 'photo' | 'voice' | 'link';

/**
 * Normalized context gathered from the home composer before the questions.
 * A single shape for all four input types keeps every downstream screen and the
 * edge function type-agnostic; type-specific fields are simply left undefined.
 */
export interface UnpackContext {
    type: UnpackEntryType;
    /** Typed text (text entries) or caption (photo/voice/link entries). */
    text: string;

    // ── Photo ────────────────────────────────────────────────────────────
    /** Local URI of the picked/optimized image (persisted only on Save). */
    photoLocalUri?: string | null;
    /** Base64 of the optimized image, sent to the vision step during enrichment. */
    imageBase64?: string | null;
    /** MIME type for the base64 image (e.g. "image/jpeg"). */
    imageMimeType?: string | null;
    /** Short factual image description returned by the vision step. */
    imageContext?: string | null;

    // ── Voice ────────────────────────────────────────────────────────────
    /** Transcript reused from the composer's voice attachment (no re-transcription). */
    transcript?: string | null;
    /** Storage path of the recorded audio (persisted only on Save). */
    voiceStoragePath?: string | null;
    voiceDurationSec?: number | null;

    // ── Shared link ──────────────────────────────────────────────────────
    sharedLink?: UnpackSharedLink | null;
}

export interface UnpackSharedLink {
    url: string;
    platform?: string | null;
    title?: string | null;
    /** Gemini content digest (fetched during enrichment; may be null on failure). */
    summary?: string | null;
    /** Source domain. */
    source?: string | null;
    mediaType?: string | null;
    thumbnailUrl?: string | null;
}

/** A single clarifying question generated by the AI. */
export interface UnpackQuestion {
    id: string;
    question: string;
}

/** The user's answer to a clarifying question. */
export interface UnpackAnswer {
    answer: string;
    skipped: boolean;
}

/** The generated reflection draft returned by the reflection step. */
export interface UnpackReflection {
    title: string;
    reflection: string;
    suggestedMood: string;
    themes: string[];
    insightSignals: string[];
    entryBadge?: string;
}

/** Remaining-usage envelope surfaced from the edge function's rate limiter. */
export interface UnpackUsage {
    used: number;
    limit: number;
    remaining: number;
    tier: 'free' | 'plus';
}

/**
 * Rich metadata persisted on `entries.unpack_payload` (jsonb). The polished
 * reflection text itself also lives in `note` / `ai_summary` so insights read
 * it with no changes; this payload holds the trail-only context.
 */
export interface UnpackPayload {
    version: number;
    originalEntryType: UnpackEntryType;
    originalText: string | null;
    selectedMood: string;
    mediaAttachments: string[];
    sharedLink: {
        url: string;
        title: string | null;
        summary: string | null;
        source: string | null;
    } | null;
    voiceTranscript: string | null;
    questions: {
        question: string;
        answer: string;
        skipped: boolean;
    }[];
    generatedReflection: string;
    userEditedReflection: string | null;
    themes: string[];
    insightSignals: string[];
    createdAt: string;
}

/** Current schema version for `UnpackPayload`. */
export const UNPACK_PAYLOAD_VERSION = 1;
